apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gpqs
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0071-tenant/tkrw-pr712-0075-0071-app/devfile-sample-gpqs@sha256:5c8d44bfa320be10ba3143116174a696a8d56544a2dc238a9cbc5e94841eec52
        name: my-nodejs
        resources: {}
status: {}
